name: Daily Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set Up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions@github.com"

    - name: Update File
      run: |
        echo "Last updated: $(date)" > last_update.txt
        git add last_update.txt
        git commit -m "Auto-update: $(date)" || echo "No changes to commit"

    - name: Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git remote set-url origin https://Hardeep56:${GH_PAT}@github.com/Hardeep56/daily-commit-bot.git
        git push
